#!/usr/bin/env python
"""
Forked from https://gist.github.com/810399
"""
from __future__ import with_statement, print_function
import os
import re
import subprocess
import sys
import pycodestyle


options = {
# don't fill in both of these
        'select': [
            ],
        'ignore': [
            ],
        }


def system(*args, **kwargs):
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return out


def main():
    modified = re.compile('^[AM]+\s+(?P<name>.*\.py$)', re.MULTILINE)
    files = system('git', 'status', '--porcelain').decode("utf-8")
    files = modified.findall(files)

    if options['select'] and options['ignore']:
        print(u'Error: select and ignore codes are mutually exclusive')
        sys.exit(1)

    checker = pycodestyle.StyleGuide(**options)

    report = checker.check_files(paths=files)


    if report.total_errors != 0:
        print('''PEP8 style violations have been detected.  Please fix them
        or force the commit with "git commit --no-verify".''')
        sys.exit(1)


if __name__ == '__main__':
    main()
